import './globals.css'
import type { Metadata } from 'next'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'], weight: '400', display: 'swap' })

export const metadata: Metadata = {
  title: 'Solemarket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <title>Home / X</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
